# This file defines the contenttypes on the website. See the documentation for
# details: http://docs.bolt.cm/content#defining-contenttypes
news:
    name: News
    singular_name: Newsitem 
    fields:
        title:
            type: text
            class: large
        slug:
            type: slug
            uses: title
        image:
            type: image             
        text:
            type: html
            height: 300px  
            allowtwig: true
        text_markdown:
            type: markdown
            height: 400px  
#        text2:
#            type: html
#            height: 300px              
    record_template: newsitem.twig
    listing_template: newslisting.twig
    sort: -id
 
features:
    name: Features
    singular_name: Feature
    fields:
        title:
            type: text
            class: large
        slug:
            type: slug
            uses: title
        image:
            type: image             
        text:
            type: html
            height: 300px  
    record_template: newsitem.twig
    listing_template: features.twig
    sort: title
    taxonomy: [ chapters ]
    recordsperpage: 100
    
 

homepage:
    name: Homepage
    singular_name: Home
    fields:
        title:
            type: text
            class: large
        slug:
            type: slug
            uses: title
        subtitle:
            label: Ondertitel
            type: text
            class: wide
        block1:
            type: html
            height: 150px
        block2:
            type: html
            height: 150px
        block3:
            type: html
            height: 150px
    template: index.twig


pages:
    name: Pages
    singular_name: Page
    fields:
        title:
            type: text
            class: large   
        slug:
            type: slug
            uses: title                    
        subtitle:
            type: text
        image:
            type: image
        body:
            type: html
            height: 300px
        template:
            label: Choose a template..
            type: templateselect 
            filter: '*.twig'   
    template: page.twig
    sort: title
    recordsperpage: 100

showcases:
    name: Showcases
    singular_name: showcaseitem 
    fields:
        title:
            type: text
            class: large
        slug:
            type: slug
            uses: title
        image:
            type: image             
        sitelink:
            type: text
            class: large
    record_template: newsitem.twig
    listing_template: showcase.twig


# possible field types:
# text - varchar(256) - input type text
# number - double - input type text, useful for storing number that need to be sortable
# templateselect - varchar(256) - select with template filenames
# image - varchar(256) - image select/upload widget, stored as filename
# file - varchar(256) - file select/upload widget, stored as filename
# video - varchar(256) - Video embed widget, stored as filename
# html - text (65kb) - wysiwyg element
# textarea - varchar(32768) - < textarea >
# datetime - datetime - date and time selector widget
# date - datetime - date selector widget
# divider - simple divider to enter a short text and/or line in the edit page.
