# This file defines the menus on the website. See the documentation for
# details: http://docs.bolt.cm/menus
# TODO: Write documentation for menus. ;-)

Main:
  - label: Home
    title: The Bolt Homepage
    path: homepage
  - label: Features
    title: An overview of the features in Bolt. With screenshots!
    path: page/features  
  # - label: Screenshots
  #   title: An overview of the features in Bolt. With screenshots!
  #   link: http://docs.bolt.cm/screenshots  
  # - label: Showcase
  #   path: page/showcase
  - label: Documentation
    title: Documentation for installation, configuration and creating sites with Bolt
    link: http://docs.bolt.cm
  - label: News
    title: The latest Bolt news! Extra! Extra! Read all about it! 
    link: /page/news
  - label: Download
    path: page/download
  - label: User manual
    title: Manual for 'working with Bolt', specifically for endusers and editors.
    link: http://manual.bolt.cm
